# Generated by Django 5.0.4 on 2024-05-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_cargo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargo',
            new_name='Cargos',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.cargos'),
            preserve_default=False,
        ),
    ]
