# Generated by Django 5.0.4 on 2024-05-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_rename_cargo_cargos_pessoa_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.pessoa')),
            ],
        ),
    ]
